routes['default_controller'] = 'Users'
routes['users/logreg'] = 'Users#logreg'
routes['/users/vendor'] = 'Users#vendor'
routes['/users/contractor'] = 'Users#contractor'
routes['/users/search'] = 'Users#search'
routes['/users/show/<user_id>'] 'Users#show'
routes['/users/userlist'] 'Users#userlist'
routes['/bids/<job_id>'] 'Bids#show'
routes['/jobs/joblist'] = 'Jobs#Joblist'
routes['/jobs/view/<job_id>'] = 'Jobs#view'
routes['/jobs/search'] = 'Jobs#search'
routes['POST']['/users/add']='Users#add'
routes['POST']['/users/login']='Users#login'
routes['POST']['/users/logout']='Users#logout'
routes['POST']['/users/update/<user_id>'] = 'Users#update'
routes['POST']['/Jobs/post'] = 'Jobs#add'
routes['POST']['/Jobs/update/<job_id>'] = 'Jobs#update'
routes['POST']['/bids/add/<job_id>'] = 'Bids#add'
routes['POST']['/bids/counter/<bid_id>'] = 'Bids#counter'
routes['POST']['/bids/accept/<bid_id>'] = 'Bids#accept'
routes['POST']['/jobs/confirm/<job_id>'] = 'Jobs#confirm'


